#!/bin/bash

BASE="/home/d6f/.config/dwm"

run_dwm() {                                                                                                                                        
  while true; do                                                                                                                                   
    $BASE/bin/dwm 2> /tmp/dwm.log                                                                                                                  
  done                                                                                                                                             
} 

run_dwmblocks() {
  while true; do                                                                                                                                   
  	$BASE/bin/dwmblocks 2> /tmp/dwm.log
  done                                                                                                                                             
}

run_gnome() {
  gnome-flashback &
  gnome-screensaver &
  /usr/libexec/gsd-a11y-settings &
  /usr/libexec/gsd-backlight-helper &
  /usr/libexec/gsd-color &
  /usr/libexec/gsd-datetime &
  /usr/libexec/gsd-disk-utility-notify &
  /usr/libexec/gsd-housekeeping &
  /usr/libexec/gsd-keyboard &
  /usr/libexec/gsd-media-keys &
  /usr/libexec/gsd-power &
  /usr/libexec/gsd-printer &
  /usr/libexec/gsd-print-notifications &
  /usr/libexec/gsd-rfkill &
  /usr/libexec/gsd-screensaver-proxy &
  /usr/libexec/gsd-sharing &
  /usr/libexec/gsd-smartcard &
  /usr/libexec/gsd-sound &
  /usr/libexec/gsd-usb-protection &
  /usr/libexec/gsd-wacom &
  /usr/libexec/gsd-wacom-oled-helper &
  /usr/libexec/gsd-wwan &
  /usr/libexec/gsd-xsettings &
}

oneshot() {
  setxkbmap -layout us,ru -option 'grp:lalt_lshift_toggle'
  xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
  xinput set-prop "ELAN1200:00 04F3:30BA Touchpad" "libinput Tapping Enabled" 1
  xinput set-prop "SYNA8009:00 06CB:CE57 Touchpad" "libinput Tapping Enabled" 1
}

daemons() {
  $BASE/bin/picom-smooth --config $BASE/picom.conf --experimental-backend &
  /usr/lib/x86_64-linux-gnu/xfce4/notifyd/xfce4-notifyd &
  diodon &

  sh -c 'dbus-monitor --session "type='\''signal'\'',interface='\''org.gnome.ScreenSaver'\''" | while read x; do case "$x" in *'\''boolean true'\'') true;; *'\''boolean false'\'') xset dpms 0 && pkill -CONT xfce4-notifyd && pkill -CONT dwmblocks && pkill -CONT gnome-flashback;; esac; sleep 1; done' &
}

run_autostart() {
  oneshot &
  daemons &
  dbus-update-activation-environment --all
}
                                                                                                                                                  
run_dwm &
run_gnome &
run_dwmblocks &
run_autostart &

sleep infinity
